//
// Created by Administrator on 2025/5/24.
//

#ifndef NET_CONFIG_H
#define NET_CONFIG_H

#define DEBUG_ETHER DEBUG_INFO
#define DEBUG_NETIF DEBUG_INFO
#define DEBUG_INIT DEBUG_INFO
#define DEBUG_PLAT DEBUG_INFO
#define DEBUG_MSG DEBUG_INFO
#define DEBUG_BUF DEBUG_INFO
#define DEBUG_M_BLOCK DEBUG_ERROR
#define DEBUG_QUEUE DEBUG_ERROR
#define DEBUG_NO_FREE_BLCK DEBUG_ERROR

#define NET_ENDIAN_LITTLE

#define EXMSG_MSG_CNT 10
#define LOCKER_TYPE N_LOCKER_THREAD
#define PKT_BLK_SIZE 128
#define PKT_BLK_CNT 128
#define PKT_BUF_CNT 128

#define NETIF_HWADDR_SIZE   6
#define NETIF_NAME_SIZE     10
#define NETIF_INQ_SIZE        50
#define NETIF_OUTQ_SIZE       50

#define NETIF_DEV_CNT       10

#endif //NET_CONFIG_H