//
// Created by Administrator on 2025/5/24.
//

#ifndef NET_CONFIG_H
#define NET_CONFIG_H

#define DEBUG_INIT DEBUG_INFO
#define DEBUG_PLAT DEBUG_INFO
#define DEBUG_MSG DEBUG_INFO
#define DEBUG_BUF DEBUG_INFO
#define DEBUG_M_BLOCK DEBUG_ERROR
#define DEBUG_QUEUE DEBUG_ERROR
#define DEBUG_NO_FREE_BLCK DEBUG_ERROR

#define EXMSG_MSG_CNT 10
#define LOCKER_TYPE N_LOCKER_THREAD
#define PKT_BLK_SIZE 128
#define PKT_BLK_CNT 128
#define PKT_BUF_CNT 128

#endif //NET_CONFIG_H
